flowchart TD
    %% Users
    n15([Reviewer])

    %% Scope
    subgraph 08["Scope"]

        %% User
        n2([Developer])

        %% Auth
        subgraph 05["Authn/Authz"]
            n11["Authn"]
            n12["Authz"]
        end

        %% Workstation
        subgraph 02["Workstation"]
            n3["Local codebase clone"]
            n4["IDE"]
            n5["Assistant Plugin"]
        end

        %% Agent Tools (e.g.: https://www.qodo.ai/mcp-plugins/)
        subgraph 06["Agent Tools"]
            n17["Extension(s) / MCP Tool(s)"]
        end

        %% Services
        subgraph 07["Service"]
            n18["Service(s) e.g., Jira, GitHub"]
        end

        %% Cloud Assistant
        subgraph 04["Cloud Service (Assistant)"]
            n6["Assistant Backend"]
            n7["Assistant LLM"]
        end

    end

    %% Remote / SCM
    subgraph 01["SCM (Server / Cloud)"]
        n1["Remote codebase"]
        n13["Pull Request (SCM)"]
        n14["SCM Policy Engine (branch protections, merge rules)"]
    end

    %% CI/CD
    subgraph 03["Change Control / CI-CD"]
        n16["clone repo"]
        n8["Build & Test Pipeline"]
        n9["Security Gate(s)"]
        n10["Code Quality Gate"]
    end

    %% Developer Auth flows
    n2 ---|"Authenticates"| n11
    n11 ---|"Authorization checks"| n12

    %% Dev local work
    n2 ---|"uses"| n4
    n4 ---|"R/W access"| n3
    n4 ---|"Context, Snippets, User Commands"| n5
    n5 ---|"Suggestions, Edits, Insertions"| n4

    %% Assistant interaction
    n5 ---|"Code prompt, edits, context"| n6
    n6 ---|"Suggestions"| n5
    n6 ---|"Processed request, context"| n7
    n7 ---|"Suggestions"| n6

    %% Assistant / Agent Tools / Service
    n5 ---|"calls (needs authn/z)"| n17
    n17 ---|"calls (needs authn/z)"| n18
    n18 -.->|"authn/z"| n11

    %% Git / PR / Pipeline / Merge flow
    n1 ---|"cloned to (with authn/authz)"| n3
    n3 ---|"push branch (with authn/authz)"| n13
    n13 ---|"triggers"| n8
    n16 ---|"code copy now in pipeline"| n8
    n1 ---|"repo clone for build (with authn/authz)"| n16
    n8 <-->|"security enforcement"| n9
    n8 <-->|"quality enforcement"| n10
    n8 ---|"status: pass/fail"| n13

    %% Reviewer optional step
    n15 -.->|"optional: review / approve"| n13

    %% Policy Engine controls merge
    n13 ---|"evaluates PR (pipeline + reviewer + rules)"| n14
    n14 ---|"update code"| n1

    %% SCM -> Authn/Authz
    n14 -.->|"authn check"| n11
    n14 -.->|"authorization enforcement"| n12
	style 08 color:#000000,fill:#C1FF72